### ISSUE TITLE
meaning of errflag 3

### ISSUE THREAD

**Issue by yiyimanew** [DavisBrian/seqMeta#18]
Hi Brian,
What does the errflag 3 at the meta-analysis stage of the seqmeta mean? I have encountered one problem is that all the individual analysis are fine with errflag 0 and a valid P value, but the meta-analysis has NA for P value and the errflag is 3. So I am wondering what does errflag 3 mean and I want to know whether there is any way I can fix that.

Thanks!
Yiyi

**Comment by DavisBrian** [comment]
@yiyimanew 

Sorry that the documentation is unclear on this issue. skatO relies on some numerical integration, using R's `integrate' function. The integrand itself is a little complicated, made of functions from the CompQuadForm package which occasionally throw errors themselves. Errflag=2 means that`integrate' suspects the integral may be inaccurate, while errflag=3 typically means there was trouble evaluating the integrand at some point, at which point seqMeta defaults to the `liu' method. It's hard to comment on whether the p-value is meaningfully inaccurate without really drilling down into it.
