### ISSUE TITLE
what is the lowest P value can seqMeta reach except for 0?

### ISSUE THREAD

**Issue by yiyimanew** [DavisBrian/seqMeta#19]
Hi Brian,
I was using skato in seqMeta to do the meta-analysis across 24 cohorts for one region. Each cohort shows valid P value and the errflag=0. For example, one cohort has P at the level of 10-61, another cohort has the P value at the level of 10-40, many other cohorts have the P at the level of 10-10 to 10-20. However, the meta-p value showed 0. I am guessing is it because the meta-P value is too low, say something around 10-100 level, so the final meta-P value was rounded to 0? 

May I ask you what is the minimum meta-P value can reach except for 0? Also, what does the P value as 0 mean? 

Thank you very much!

Yiyi

**Comment by DavisBrian** [comment]
@yiyimanew I suspect you are running into numerical precision issues and your meta -p value is so small it is indistinguishable from 0.  An actual p-value of 0 would indicate your sample was impossible under the null hypothesis.

The smallest non-zero number is going to be determined by your computer architecture and operating system.  In R you can use .Machine to see these numerical limits.

Also, I'd refer you to the "Notes" in the skatOmeta help file about p-values with skatO.

Brian

**Comment by yiyimanew** [comment]
Thank you for your reply. I have tried both SKAT and burden, I got the same 0 p value. I have test the limit of R on my machine and it seems that the 10-308 is the lowest one I can get.

However, how can I exactly tell the difference between a true 0 p value and the too small P value? I am not sure whether it is OK for me to put the 10-308 as the p values for my case or they are truly having 0 p value.

Thanks!

Yiyi

**Comment by DavisBrian** [comment]
@yiyimanew 
From a theoretical prospective if you have a valid scores and variance then you would have a non-zero p value.  (i.e. What would give you a p-value of 0 on a chi-sq distribution?).

Since really small p-values are imprecise anyways you might want to report p values smaller than some threshold as  << "threshold" much like the lm function does.  Where that threshold is would be up to you.

Brian
