### ISSUE TITLE
Error in which(ISNAZ) : long vectors not supported yet

### ISSUE THREAD

**Issue by vsvinti** [DavisBrian/seqMeta#32]
Hi there

I am getting an error when trying to run prepScores2 with a particular dataset that has a lot of NAs:
<pre>
obj2 <- prepScores2(Z=Z, formula=PHENOTYPE~SEX, SNPInfo=SNPInfo, data=pheno, family = "binomial")

Error in which(ISNAZ) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:138
</pre>
My Z matrix has 2557 rows and 848320 columns , and quite a lot of NAs . This command is called from the impute_to_mean function. 

How can I get around this problem? I have tried it with R 3.2.4 and R.3.3.2, but I get the same errors. 

Thanks
Vicky

**Comment by DavisBrian** [comment]
@vsvinti I suspect you'll need to break up your genotype matrix into multiple matrices.

**Comment by vsvinti** [comment]
I see. I am using the output of plink --recodeA, which is a genotype matrix where rows are individuals and columns are variants. So when you say break up the matrix, assuming you mean by columns (by subsetting variants), but making sure ones that fall within the same gene are in the same set?

**Comment by vsvinti** [comment]
Splitting my matrix into 2 subsets (as mentioned above) seemed to generated prepScores objects successfully! Thanks!

**Comment by DavisBrian** [comment]
great!

**Comment by vsvinti** [comment]
Brian, can I ask one more question on this: how can I combine two seqMeta objects (generated from running prepScores2 on different section of a genotype matrix)? I have lots of combinations of metas to run downstream, and merging this into one seqMeta object would simplify things a bit. I have done c(obj1, obj2), which looks alright but class of outcome is now a list (and I am unsure if objects merged properly).

**Comment by DavisBrian** [comment]
Are you using the latest version (1.6.7) of seqMeta?  This was an issue (#26), but should be fixed (in 1.6.6).  The class of your new object should be "seqMeta".  You may be able to get around the bug if you are using an older version by directly calling c.seqMeta(obj1, obj2)

**Comment by vsvinti** [comment]
You are right - I had loaded 1.6.6 for trying this, but 1.6.7 returns a seqMeta. Thanks!
