### ISSUE TITLE
prepScores for familial dataset

### ISSUE THREAD

**Issue by vifehe** [DavisBrian/seqMeta#37]
When running prepscores for a familial dataset I get one error that I don;t know how to interpret:
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘forceSymmetric’ for signature ‘"data.frame", "missing"’

my kinship matrix was generated with kinship2.

any help will be much appreciated

thanks

V

**Comment by DavisBrian** [comment]
Please make an reproducible example.  For examples please see https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example or https://www.r-bloggers.com/minimal-reproducible-examples/

With R 3.5.0 there are some know build errors with Matrix and coxme packages (see CRAN).  Could very well be you ran into one of those.

**Comment by vifehe** [comment]
Hi,

thanks for the reply. I have tried with version 3.3 of R and I still get the same error. However, I think I have narrowed down the problem. My kinship is a data.frame, whereas the example kinship provided is a "dsCMatrix". Could it be the error? if so, could you advise on the best commands to convert the data.frame to the adequate kind of matrix?

## My original is a data.frame that I convert into matrix as: 
famkin2<-data.matrix(fam.kin, rownames.force=NA)

## force conversion of matrix to symmetric matrix:
library(Matrix)
famkin3<-forceSymmetric(famkin2)

but then when I try to generate the prepscores I get the error:
"Error in as(x, "bdsmatrix") : 
  no method or default for coercing “dsyMatrix” to “bdsmatrix”

I can generate the example files still if needed.

Thanks

V

**Comment by DavisBrian** [comment]
That's definitely the issue.  You'll need to convert from a data fame to the appropriate sparse matrix.  There is probably an example of how to do this in Matrix package documentation.  You might have to take the intermediate step of first converting to a matrix then a sparse matrix but I'm not sure off the top of my head.

I'm going to close this issue as it's not a seqMeta issue and could probably be answered better on Stackoverflow.
