### ISSUE TITLE
error in using PrepScores2

### ISSUE THREAD

**Issue by elise625** [DavisBrian/seqMeta#39]
I'm using prepScores2 function. I have the genotypes, phenotypes, snpinfo files prepared just like the example data in the package. 
I keep getting this following error and I was wondering where I'm going wrong with this? 
I tried switching the SNP names to just be numeric, removing rownames for genotype matrix, etc but nothing seems to be working.

Error in base::colMeans(x, na.rm = na.rm, dims = dims, ...) :
  'x' must be numeric

**Comment by DavisBrian** [comment]
@elise625 Without a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) I would be taking a stab in the dark.  Judging from the error message it appears the genotype matrix is not a numeric matrix.   What does `str` give you on your genotype matrix?

**Comment by elise625** [comment]
Yes that was the problem. Thank you!
