### ISSUE TITLE
cmaf greater than 1?

### ISSUE THREAD

**Issue by elise625** [DavisBrian/seqMeta#41]
Hello,

I'm performing meta analysis using skatMeta function for rare variants with maf < 0.05. 
I have 5 cohorts in my meta analysis and for a lot of genes, i'm getting cmaf greater than 1. 
I'm having trouble explaining this since these are all variants with maf < 0.05 in individual cohorts? I don't have many snps in the gene either so I can't explain cmaf being so big?

also is there internal filtering done? It seems like the number of snps inputted doesn't match the output in meta-analysis.

**Comment by DavisBrian** [comment]
@elise625  Please provide a minimal, self-contained, and reproducible example by reducing your example as much as possible right before the problem goes away.  Please include your session info with `devtools::session_info()` and the structure (`str()`) of your phenotype, genotype, and snpinfo dataset.

**Comment by DavisBrian** [comment]
No reproducible example provided.
