### ISSUE TITLE
error in survival analysis

### ISSUE THREAD

**Issue by trptyrphe11** [DavisBrian/seqMeta#45]
Hi, 

I got the error "Error in cbind(Z0[, zvar != 0], X) : number of rows of matrices must match (see arg 2)" when I am trying to perform prepCox. What does the error come from? Thanks.

**Comment by DavisBrian** [comment]
Please provide a reproducible example.

**Comment by trptyrphe11** [comment]
Ok, found the cause was in prepCox, coxph returns fewer rows (for those with NAs are removed).
