### ISSUE TITLE
is there a way to include interaction term in the formula for survival data?

### ISSUE THREAD

**Issue by trptyrphe11** [DavisBrian/seqMeta#46]
Hi,

I am using seqMeta to perform Cox survival analysis with gene-based method. I am wondering is it possible to include the interaction term (gene * environment) in addition to the standard formula (prepCox(data, Surv(endpoint) ~ gender)? Thanks.

**Comment by DavisBrian** [comment]
@trptyrphe11 For general questions, please ask them on StackOverflow first, using the `r` tag: http://stackoverflow.com/questions/ask Please come back here only if nobody answers your question there, and let me know the URL of your StackOverflow post. If you are not sure whether to post a StackOverflow question or open a Github issue, do the former first.

**Comment by trptyrphe11** [comment]
Hi, this is seqMeta specific question: I know how to perform coxph survival
analysis including the interaction term, but I don't know the syntax in
seqMeta. Thanks.

**Comment by enigmargs** [comment]
Hi @trptyrphe11, I am planning on using this package for survival analysis. Did you get your way around the issue that you have asked?

Thanks for your help.
